### ISSUE TITLE
Error when running example in ?plotstruct

### ISSUE THREAD

**Issue by Henrik-P** [snoweye/phyclust#4]
I'm using `phyclust_0.1-22`. When I try the first example in `?plotstruct`, I get an error.
```
set.seed(1234)
ret.1 <- phyclust(seq.data.toy$org, 3)
plotstruct(ret.1$Z.normalized)
# Error in tmp.Z[, k] : incorrect number of dimensions
```

**Comment by snoweye** [comment]
Thanks, @Henrik-P. This should be fixed now at [here](https://github.com/snoweye/phyclust).
