### ISSUE TITLE
Error in haplo.post.prob

### ISSUE THREAD

**Issue by mangiruben** [snoweye/phyclust#7]
In 2016, I ran the haplo.post.prob function and completed analysis successfully. I am re-running the same data now and am getting this error
(Error in (theta^(mut.step - ss)) %*% diag(poolPI) : 
  requires numeric/complex matrix/vector arguments)
Could you please help me out

**Comment by snoweye** [comment]
[This](https://github.com/snoweye/phyclust/blob/master/R/tzeng-code.getPIstar.getBigMatB.r#L142-L143) and [this](https://github.com/snoweye/phyclust/blob/master/R/tzeng-code.getPIstar.getBigMatB.r#L212-L213) should fix the problem. Please use version 0.1-32 for a newer R. Thanks.
